name: popcorn
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  dio: ^3.0.10
  http: ^0.12.2
  bloc: ^6.1.1
  rxdart: ^0.25.0
  eva_icons_flutter: ^2.0.1
  page_indicator: ^0.3.0
  sliver_fab: ^1.0.0
  flutter_spinkit: ^4.1.2+1
  youtube_player_flutter: ^7.0.0+7

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
